services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    ports:
      - 3000:8080
    volumes:
      - ./data/keycloak_data:/opt/keycloak/data
    networks:
      - local
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   networks:
  #     - local
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - keycloak

networks:
  local:
    driver: bridge
